version: "3.7"
services:
  ProjectZomboidDedicatedServer:
    image: danixu86/project-zomboid-dedicated-server:latest
    container_name: pz-monga
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    volumes:
      - ./data:/home/steam/Zomboid
      - ~/workshop-mods/project-zomboid:/home/steam/pz-dedicated/steamapps/workshop

# Workshop mods folder
# /home/steam/pz-dedicated/steamapps/workshop

# Server data
# /home/steam/Zomboid

# WORKSHOP_IDS
# 2998815983;2923439994;2464581798;2625625421;2931593489;2487022075;2648779556;2875848298;2849247394;2859296947;2859296947;2859296947

# MOD_IDS
# Jump;MoreSmokes;waterPipes;isoContainers;QuickWeedReborn;TMC_TrueActions;TrueActionsDancing


