name: deploy container docker
on:
  pull_request:
    branches:    
      - deploy-container-docker

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          
    - name: Clone repository
      run: git clone git@github.com:MongaGit/monga-container-server.git
