name: deploy container docker
on: workflow_dispatch

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
    - name: Clone GitHub repository
      run: sudo git clone git@github.com:MongaGit/monga-container-server.git

