name: deploy container docker
on: workflow_dispatch

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al 
          git clone git@github.com:MongaGit/monga-container-server.git
          sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt update
          sudo apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin

          docker compose version
          echo "docker compose version"

