name: Minecraft | Start
on: workflow_dispatch

jobs:
  clone:
    name: Minecraft Start Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker-Compose Up Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/monga/save-game-server/minecraft/mods
            echo "EULA=${{ secrets.MINECRAFT_EULA}}" >> .env
            echo "RCON_PASSWORD=${{ secrets.MINECRAFT_RCON_PASSWORD}}" >> .env
            echo "SERVER_NAME=${{ secrets.MINECRAFT_SERVER_NAME}}" >> .env
            echo "DIFFICULTY=${{ secrets.MINECRAFT_DIFFICULTY}}" >> .env
            echo "MAX_PLAYERS=${{ secrets.MINECRAFT_MAX_PLAYERS}}" >> .env
            echo "MOTD=${{ secrets.MINECRAFT_MOTD}}" >> .env
            echo "ICON=${{ secrets.MINECRAFT_ICON}}" >> .env
            echo "CF_API_KEY: ${{secrets.MINECRAFT_CF_API_KEY}}" >> .env
            echo "Docker-Compose Up | Minecraft Server Starting"
            cd /home/monga/save-game-server/minecraft/mods && docker-compose up -d
      
      - name: Delte .env File
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ###rm -rf .env
            ###cd /home/monga/save-game-server/minecraft/mods && rm -rf .env

