name: Minecraft | Start
on: workflow_dispatch

jobs:
  clone:
    name: Minecraft Start Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker-Compose Up Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/monga/save-game-server/minecraft/
            echo "MINECRAFT_EULA=${{ secrets.MINECRAFT_EULA}}" >> .env
            echo "MINECRAFT_RCON_PASSWORD=${{ secrets.MINECRAFT_RCON_PASSWORD}}" >> .env   
            echo "RWA_RCON_PASSWORD=${{ secrets.MINECRAFT_RCON_PASSWORD}}" >> .env
            echo "RWA_PASSWORD=${{ secrets.MINECRAFT_RCON_PASSWORD}}" >> .env
            echo "RCON_PASSWORD=${{ secrets.MINECRAFT_RCON_PASSWORD}}" >> .env
            echo "MINECRAFT_SERVER_NAME=${{ secrets.MINECRAFT_SERVER_NAME}}" >> .env
            echo "MINECRAFT_DIFFICULTY=${{ secrets.MINECRAFT_DIFFICULTY}}" >> .env
            echo "MINECRAFT_MAX_PLAYERS=${{ secrets.MINECRAFT_MAX_PLAYERS}}" >> .env
            echo "MINECRAFT_MOTD=${{ secrets.MINECRAFT_MOTD}}" >> .env
            echo "MINECRAFT_ICON=${{ secrets.MINECRAFT_ICON}}" >> .env
            echo "Docker-Compose Up | Minecraft Server Starting"
            cd /home/monga/save-game-server/minecraft && docker-compose up -d --build
      
      - name: Delte .env File
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf .env
            cd /home/monga/save-game-server/minecraft && rm -rf .env
