name: Project-Zomboid Start Server
on: workflow_dispatch

jobs:
  clone:
    name: Project-Zomboid Start Server
    runs-on: ubuntu-latest
    steps:
    - name: Project-Zomboid Start Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            echo "Pull the latest image"
            docker pull renegademaster/zomboid-dedicated-server:latest

            echo "Make two folders"
            mkdir ZomboidConfig ZomboidDedicatedServer

            echo "Run the server"
            docker run --detach \
                --mount type=bind,source="$(pwd)/game-data/project-zomboid/data",target=/home/steam/ZomboidDedicatedServer \
                --mount type=bind,source="$(pwd)/game-data/project-zomboid/config",target=/home/steam/Zomboid \
                --publish 16261:16261/udp --publish 16262:16262/udp \
                --name monga-project-zomboid \
                docker.io/renegademaster/zomboid-dedicated-server:latest \
