name: Project-Zomboid | Backup save
on: workflow_dispatch

jobs:
  clone:
    name: Connect to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/monga/save-game-server/project-zomboid
            git reset --hard HEAD
            git add .
            git commit -m "PROJECT-ZOMBOID: Backup Monga data"
            git push -u origin main --force
            
