name: teste
on: workflow_dispatch

jobs:
  clone:
    name: teste
    runs-on: ubuntu-latest
    steps:
    - name: Project-Zomboid Start Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}

    container:
      image: danixu86/project-zomboid-dedicated-server:latest

    env:
        ADMINPASSWORD: ${{ vars.ADMINPASSWORD }}
        DEBUG: ${{ vars.DEBUG }}
        MODFOLDERS: ${{ vars.MODFOLDERS }}
        MOD_IDS: ${{ vars.MOD_IDS }}
        NOSTEAM: ${{ vars.NOSTEAM }}
        PORT: ${{ vars.PORT }}
        SERVERNAME: ${{ vars.SERVERNAME }}
        STEAMVAC: ${{ vars.STEAMVAC }}
        WORKSHOP_IDS: ${{ vars.WORKSHOP_IDS }}
