name: Teste
on: workflow_dispatch

jobs:
  clone:
    name: Teste
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/monga/monga-container-server/project-zomboid
            echo "ADMINPASSWORD=${{ secrets.PROJECT_ZOMBOID_ADMINPASSWORD }}"
            echo "DEBUG=${{ secrets.PROJECT_ZOMBOID_DEBUG }}"
            echo "MODFOLDERS=${{ secrets.PROJECT_ZOMBOID_MODFOLDERS }}"
            echo "MOD_IDS=${{ secrets.PROJECT_ZOMBOID_MOD_IDS }}"
            echo "NOSTEAM=${{ secrets.PROJECT_ZOMBOID_NOSTEAM }}"
            echo "PORT=${{ secrets.PROJECT_ZOMBOID_PORT }}"
            echo "SERVERNAME=${{ secrets.PROJECT_ZOMBOID_SERVERNAME }}"
            echo "STEAMVAC=${{ secrets.PROJECT_ZOMBOID_STEAMVAC }}"
            echo "WORKSHOP_IDS=${{ secrets.PROJECT_ZOMBOID_WORKSHOP_IDS }}"
            echo "Docker-Compose Up | Project-Zomboid Server Starting"
            
