name: Valheim | Backup
on: workflow_dispatch

jobs:
  clone:
    name: Connect to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/monga/save-game-server/valheim
            git reset --hard HEAD
            git add .

            # Exclui arquivos que não são necessários para o commit
            git rm --cached path/to/excluded_file1
            git rm --cached path/to/excluded_file2

            git commit --amend -CHEAD
            git push origin main --force
