name: V Rising | Backup
on: workflow_dispatch

jobs:
  clone:
    name: Connect to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/monga/save-game-server/project-zomboid
            git reset --hard HEAD
            git add .

            cd /home/monga/save-game-server/vrising/server/
            git rm --cached GameAssembly.dll 

            cd /home/monga/save-game-server/vrising/server/VRisingServer_Data/
            git rm --cached globalgamemanagers.assets


            git commit --amend -CHEAD -m "VRISING: Backup Monga data"
            git push origin main --force
            
